package de.raimannma.reinforce4j;

public enum Option {
    GAMMA, EPSILON, ALPHA, EXPERIENCE_ADD_EVERY, EXPERIENCE_SIZE, LEARNING_STEPS_PER_ITERATION, TD_ERROR_CLAMP, SAVE_INTERVAL, NUM_HIDDEN_UNITS
}
